name: xmpp_stone

description: "Xmpp Stone is lightweight XMPP client library written completely in Dart."

version: 0.1.3

authors:
  - Nemanja Vukoje <nemanja.vukoje@gmail.com>

homepage: (to be added)

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  xml: ^3.4.1
  cryptoutils: ^0.4.0
  crypto: ^2.0.6
  synchronized: ^2.1.0
  tuple: ^1.0.2
  unorm_dart: ^0.1.1
  image: ^2.0.7
  quiver: '>=2.0.0 <3.0.0' #hash code generator
  console: ^3.1.0 #for example

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.0.0
